services:
  web_ssl:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: "./docker/development/Dockerfile"
    command: ["bundle", "exec", "rails", "s", "-b", "ssl://0.0.0.0?key=/tmp/localhost.key&cert=/tmp/localhost.crt"]
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    ports:
      - 443:3000
    env_file:
      - .env
    depends_on:
      - db
    networks:
      main:
        aliases:
          - web
          - app.lvh.me
  web:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: "./docker/development/Dockerfile"
    command: bash -c "bin/rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    ports:
      - 3000:3000
      - 80:3000
    env_file:
      - .env
    depends_on:
      - db
    networks:
      main:
        aliases:
          - web
          - app.lvh.me
  sidekiq:
    build:
      context: .
      dockerfile: "./docker/development/Dockerfile"
    command: bundle exec sidekiq
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    depends_on:
      - db
      - redis
    networks:
      main:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    networks:
      main:
        aliases:
          - db
  redis:
    image: redis
    restart: always
    env_file:
      - .env
    networks:
      main:
        aliases:
          - redis
  adminer:
    image: adminer
    restart: always
    networks:
      main:
        aliases:
          - adminer.lvh.me
    env_file:
      - .env
    ports:
      - 8080:8080
volumes:
  bundle:
networks:
  main:
